USE techblog
GO
CREATE TABLE tblUser
(
	IDUser INT IDENTITY(1,1) PRIMARY KEY,
	FirstName VARCHAR(40) NOT NULL,
	LasttName VARCHAR(40) NOT NULL,
	Email VARCHAR(40) UNIQUE NOT NULL,
	Password VARCHAR(40) NOT NULL,
	UserRole VARCHAR(40) NOT NULL,
)

CREATE TABLE tblAdditionalUserData
(
	IDAdditionalData INTEGER PRIMARY KEY,
	FirstName VARCHAR(40) NOT NULL,
	LastName VARCHAR(40) NOT NULL,
	Info VARCHAR(500) NOT NULL,
	CONSTRAINT fk_data_user
	FOREIGN KEY (IDAdditionalData)
	REFERENCES tblUser (IDUser)
    ON DELETE CASCADE
)

CREATE TABLE tblTopic
(
	IDTopic INTEGER IDENTITY(1,1) PRIMARY KEY,
	TopicTitle VARCHAR(40) NOT NULL,
	IDUserPostAdmin INTEGER NOT NULL,
	CONSTRAINT fk_topic_user
	FOREIGN KEY (IDUserPostAdmin)
	REFERENCES tblUser (IDUser)
    ON DELETE CASCADE
)

CREATE TABLE tblMessage
(
	IDMessage INTEGER IDENTITY(1,1) PRIMARY KEY,
	MsgText VARCHAR(2000) NOT NULL,
	LikesMessage INTEGER NOT NULL DEFAULT(0),
	IDTopic INTEGER NOT NULL,
	IdUser INTEGER NOT NULL,
	CONSTRAINT fk_msg_topic
	FOREIGN KEY (IDTopic)
	REFERENCES tblUser (IDUser)
    ON DELETE CASCADE,
	CONSTRAINT fk_msg_user
	FOREIGN KEY (IdUser)
	REFERENCES tblUser (IDUser)
	ON DELETE NO ACTION
)

-- sp_rename 'tblUser.UserID', 'IDUser', 'COLUMN';
